### PR TITLE
iotdb-client-go github actions

### PR DESCRIPTION
**Pull request by manlge**
https://github.com/manlge/iotdb-client-go/actions/runs/437344648

### CODE REVIEW

**Comment by manlge** [comment]
@jixuan1989 @JackieTien97 PTAL

**Comment by jixuan1989** [comment]
Hi, sorry for reply late.
 
Why adding a method `GetValueAt` ?

**Comment by manlge** [comment]
e.g.

**Comment by manlge** [comment]
e.g.

func validate(tablet *client.Tablet) (err error) {
	temperatureColumn := 2
	for i := 0; i < tablet.GetRowCount(); i++ {
		if v, err := tablet.GetValueAt(temperatureColumn, i); err == nil {
			temperature := v.(float32)
			if temperature > 42.5 || temperature < 35.1 {
				return errors.New("The temperature must be in [35..42]")
			}
		}
	}
	return err
}

**Review by jixuan1989 — APPROVED** [review]

**Pull request merged**
