### PR TITLE
Support connecting multiple nodes of the cluster

### PR DESCRIPTION
**Pull request by ijihang**
Support connecting multiple nodes of the cluster

### CODE REVIEW

**Comment by HTHou** [comment]
Hi, why is the CI not working?

**Comment by mychaow** [comment]
> Hi, why is the CI not working?

Maybe jihang's permission is not enough?

**Comment by HTHou** [comment]
> > Hi, why is the CI not working?
> 
> Maybe jihang's permission is not enough?



> > Hi, why is the CI not working?
> 
> Maybe jihang's permission is not enough?

I don't think so, Eugene-Song should have same permission, his PR was running CI however...
https://github.com/apache/iotdb-client-go/pull/21 

Can you plz try closing and reopening the PR again to see if the CI working?

**Comment by jixuan1989** [comment]
as it submit PR to the "main" branch, rather than "master"...

**Comment by mychaow** [comment]
> as the PR submits codes to the "main" branch, rather than "master"...

https://github.com/apache/iotdb-client-go/pull/26 could trigger ci work. And the repo only has main branch.

**Pull request merged**
